FE =(input("Enter Foundation English Score : 50 "))
GB =(input("Enter General Bussiness Score : 60"))
ICS =(input("Enter Introduction to Computer Systems Score :100"))
CP =(input("Enter Computer Programming Score :90"))
print("_______ Your Score ______")
print("Foundation English :",FE,)
print("General Business :",GB,)
print("Introduction to Computer Systems : ",ICS,)
print("Computer Programming :",CP,)